global.path = require("path");
global.http = require("http");
global.qs = require("querystring");
global.async = require("async");
global._ = require("underscore");
require("colors");
require('../Modules/Shared/use');
require("../System/Base/SystemEvent");
require("../System/Base/Global");
require("../System/Lib/Log/Prelaunch");
require("../System/Lib/Sockets/SockPath");
require("../System/API/FunctionExposer");
require("../System/API/EventHub");
require("./Common/Native/commands");