#!/bin/ash

CONF="/etc/dnsmasq.conf"
FULL=""
if [ "$1" == "udhcpc" ]; then
    INTERFACE=(lua /ramdisk/System/CI/ECI.lua network get wan up_interface)
    FULL="udhcpc -i "$INTERFACE
else
    PPP_NUMBER=$(lua /ramdisk/System/CI/ECI.lua network get wan ppp.number)
    FULL="pppd  unit "$PPP_NUMBER" plugin /usr/lib/pppd/2.4.7/rp-pppoe.so"
fi

FULL=$PROG" -C "$CONF
PID=0

pid(){
    echo $(ps ax | grep "$FULL" | grep -v grep | awk '{print $1}')
}

start(){
    eval $FULL
}

stop(){
    PID=$(pid)
    if [ $PID ]; then
        kill -9 $PID
    fi
}

sighup(){
    PID=$(pid)
    if [ $PID ]; then
        kill -1 $PID
    fi
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
reload|restart)
    stop
    start
    ;;
status)
    PID=$(pid)
    if [ $PID ]; then
        echo running, pid: $PID
    else
        echo not running
    fi
    ;;
sighup)
    sighup
    ;;
*)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac