#!/bin/ash

FULL_UDHCPC=""
FULL_PPPD=""

INTERFACE=$(ECI network get wan up_interface)
FULL_UDHCPC="udhcpc -b -i $INTERFACE"
PPP_NUMBER=$(ECI network get wan ppp.number)
FULL_PPPD="pppd  unit $PPP_NUMBER plugin /usr/lib/pppd/2.4.7/rp-pppoe.so"
TYPE=$1

PID=0

pid_udhcpc(){
    echo $(ps ax | grep "$FULL_UDHCPC" | grep -v grep | awk '{print $1}')
}
pid_pppd(){
    echo $(ps ax | grep "$FULL_PPPD" | grep -v grep | awk '{print $1}')
}

pid_by_cmd(){
    if [ $TYPE == "udhcpc" ]; then
        echo $(pid_udhcpc)
    else
        echo $(pid_pppd)
    fi
}

start(){
    if [ $TYPE == "udhcpc" ]; then
        eval $FULL_UDHCPC
    else
        eval $FULL_PPPD
    fi
}

stop(){
    PID=$(pid_udhcpc)
    if [ -n "$PID" ]; then
        kill -9 $PID
    fi
    PID=$(pid_pppd)
    if [ -n "$PID" ]; then
        kill -9 $PID
    fi
}

sighup(){
    PID=$(pid_by_cmd)
    if [ ! -z "$PID" ]; then
        kill -1 $PID
    fi
}

case "$2" in
start)
    start
    ;;
stop)
    stop
    ;;
reload|restart)
    stop
    start
    ;;
status)
    PID=$(pid_by_cmd)
    if [ ! -z "$PID" ]; then
        echo $PID
    else
        echo
    fi
    ;;
sighup)
    sighup
    ;;
*)
    echo $"Usage: $0 udhcpc/ppd {start|stop|restart|status|sighup}"
    exit 1
    ;;
esac