#!/bin/ash

CONF_2G="/etc/hostapd_2g.conf"
CONF_5G="/etc/hostapd_5g.conf"
PROG="hostapd"
FULL=$PROG
if [ "$1" == "2g" ]; then
    FULL=$FULL" -B "$CONF_2G
else
    FULL=$FULL" -B "$CONF_5G
fi
PID=0

pid(){
    echo $(ps ax | grep "$FULL" | grep -v grep | awk '{print $1}')
}

start(){
    eval $FULL
}

stop(){
    PID=$(pid)
    if [ $PID ]; then
        kill -9 $PID
    fi
}

sighup(){
    PID=$(pid)
    if [ $PID ]; then
        kill -1 $PID
    fi
}

case "$2" in
start)
    start
    ;;
stop)
    stop
    ;;
reload|restart)
    stop
    start
    ;;
status)
    PID=$(pid)
    if [ $PID ]; then
        echo running, pid: $PID
    else
        echo not running
    fi
    ;;
sighup)
    sighup
    ;;
*)
    echo $"Usage: $0 2g/5g {start|stop|restart|status|sighup}"
    exit 1
    ;;
esac
