global.path = require("path");
global.http = require("http");
global.fs = require("fs");
global.qs = require("querystring");
global.async = require("async");
global.child_process = require('child_process');
global._ = require("underscore");
global.wait = require("wait.for");
global.async = require("async");
global.trace = global.warn = global.error = global.fatal = global.debug = global.info = console.log;
require("colors");
require("./Common/Global");
require('../Modules/Shared/use');
require("../Modules/Shared/Crypto/HashDir");
