global.path = require("path");
global.http = require("http");
global.qs = require("querystring");
global.async = require("async");
require('../Modules/Shared/use');
require("./Base/SystemEvent");
require("./Base/Global");
require("./Lib/Log/Prelaunch");
require("./Lib/Sockets/SockPath");
require("colors");